#ssh-addkey.yml 
---
- hosts: ibmi 
  gather_facts: no 
  collections:
   - ibm.power_ibmi
  
  tasks:

  - name: install ssh key
    authorized_key: user={{ansible_ssh_user}} 
                    key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}" 
                    state=present